apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-wsom
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0056-tenant/tkrw-pr712-0075-0056-app/devfile-sample-wsom@sha256:82514de15a1f123a82df824f4463c91e432b4dc47b32d9e7735444c717cc43a0
        name: my-nodejs
        resources: {}
status: {}
